baseurl = "https://pyrypartti.fi/"
title = "Pyry Partti"
theme = "portfolio"
languageCode = "fi-fi"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "Pyry Partti portfolio"
  copyright = "&copy; 2020-2021 Pyry Partti"
  sidebarAbout = [
    "Media-alan moniosaaja, tekemällä oppija.",
  ]
  # Contact page
  [[params.email]]
  email = "portfolio@pyrypartti.fi"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Minusta"
  url = "about/"
  
  [[params.navlinks]]
  name = "CV"
  url = "about/cv/"

  [[params.navlinks]]
  name = "Nykäise hihasta"
  url = "contact/"

  [params.social]
  # instagram     = "https://www.instagram.com/"
  email         = "portfolio@pyrypartti.fi"
  linkedin      = "https://www.linkedin.com/in/pyry"
  github        = "https://github.com/profiili"
  # youtube       = "https://www.youtube.com/"
  # whatsapp      = "https://wa.me/"
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # twitter       = "full profile url in twitter"
  # stackoverflow = "full profile url in stackoverflow"
